/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppButton {
    }
    interface AppCardPiloto {
        "piloto": any;
    }
    interface AppTable {
    }
    interface AppTablePiloto {
        "piloto": any;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppCardPilotoElement extends Components.AppCardPiloto, HTMLStencilElement {
    }
    var HTMLAppCardPilotoElement: {
        prototype: HTMLAppCardPilotoElement;
        new (): HTMLAppCardPilotoElement;
    };
    interface HTMLAppTableElement extends Components.AppTable, HTMLStencilElement {
    }
    var HTMLAppTableElement: {
        prototype: HTMLAppTableElement;
        new (): HTMLAppTableElement;
    };
    interface HTMLAppTablePilotoElement extends Components.AppTablePiloto, HTMLStencilElement {
    }
    var HTMLAppTablePilotoElement: {
        prototype: HTMLAppTablePilotoElement;
        new (): HTMLAppTablePilotoElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-card-piloto": HTMLAppCardPilotoElement;
        "app-table": HTMLAppTableElement;
        "app-table-piloto": HTMLAppTablePilotoElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        "onGoBack"?: (event: CustomEvent<boolean>) => void;
    }
    interface AppCardPiloto {
        "piloto"?: any;
    }
    interface AppTable {
    }
    interface AppTablePiloto {
        "piloto"?: any;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-card-piloto": AppCardPiloto;
        "app-table": AppTable;
        "app-table-piloto": AppTablePiloto;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-card-piloto": LocalJSX.AppCardPiloto & JSXBase.HTMLAttributes<HTMLAppCardPilotoElement>;
            "app-table": LocalJSX.AppTable & JSXBase.HTMLAttributes<HTMLAppTableElement>;
            "app-table-piloto": LocalJSX.AppTablePiloto & JSXBase.HTMLAttributes<HTMLAppTablePilotoElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
